--1. Count number of services of each acteur
SELECT a.IDACTEUR as Actor_Id, COUNT(s.IDSERVICE)  as Service_Count FROM ACTORS a, SERVICES s
WHERE a.IDACTEUR = s.IDACTEUR
GROUP BY a.IDACTEUR

--2. Acteur with maximum number of services
SELECT a.IDACTEUR as Actor_Id , COUNT( s.IDSERVICE) as Service_Count
FROM ACTORS a, SERVICES s
WHERE a.IDACTEUR = s.IDACTEUR
GROUP BY a.IDACTEUR
having COUNT(s.IDSERVICE) = (SELECT MAX(tb.servicecount) 
							FROM(SELECT a.IDACTEUR actorId, COUNT(s.IDSERVICE) servicecount 
								FROM ACTORS a, SERVICES s
								WHERE a.IDACTEUR = s.IDACTEUR
								GROUP BY a.IDACTEUR)tb);

--3. SELECT services of mayor and dependent services
SELECT  a.IDACTEUR, sd.IDSERVICE1 as Service_Id1, s1.SERVICENAME as Servce_Name, 
sd.IDSERVICE2  as Service_Id2, s2.SERVICENAME as Connected_Service_Name
FROM  SERVICES s1, SERVICEDEPENDENCIES sd , SERVICES s2, ACTORS a
WHERE sd.IDSERVICE1 = s1.IDSERVICE 
AND sd.IDSERVICE2 = s2.IDSERVICE 
AND a.IDACTEUR = 'Mayor' 
AND (a.IDACTEUR = s1.IDACTEUR  
	OR a.IDACTEUR = s2.IDACTEUR);

--4. List all the services with its input and output.
SELECT vi.NAMEVARIABLE, s.SERVICENAME, vo.NAMEVARIABLE
FROM SERVICES s, SERVICEINPUT i, SERVICEOUTPUT o, VARIABLES vi, VARIABLES vo
WHERE s.IDSERVICE = i.IDSERVICE 
AND s.IDSERVICE = o.IDSERVICE 
AND vi.NUMVARIABLE = i.NUMVARIABLE 
AND vo.NUMVARIABLE = o.NUMVARIABLE

--5. List all the services which are not having output.
SELECT s.SERVICENAME
FROM SERVICES s
WHERE s.SERVICENAME NOT IN (SELECT s.SERVICENAME
						FROM SERVICES s, SERVICEOUTPUT o
						WHERE s.IDSERVICE = o.IDSERVICE )

--6. List all the services which are not having input.
SELECT s.SERVICENAME
FROM SERVICES s
WHERE s.SERVICENAME NOT IN (SELECT s.SERVICENAME
						FROM SERVICES s, SERVICEINPUT i
						WHERE s.IDSERVICE = i.IDSERVICE )

--7. List the services having choice user and system
SELECT s.SERVICENAME, c.NATURE
FROM SERVICES s, CHOICE c, SERVICECHOICE sc
WHERE s.IDSERVICE = sc.IDSERVICE AND sc.IDCHOICE = c.ID_CHOICE 

--8. List services having more than one input
SELECT i.IDSERVICE as Service_Id, COUNT(i.NUMVARIABLE) as Input_Count
FROM SERVICEINPUT i, SERVICES s
WHERE s.IDSERVICE = i.IDSERVICE
GROUP BY i.IDSERVICE
having COUNT(i.NUMVARIABLE) >1;

--9. List acteurs who do only one  service
SELECT a.IDACTEUR as Actor_Id, COUNT(s.IDSERVICE) as Service_Count
FROM SERVICES s, ACTORS a
WHERE s.IDACTEUR = a.IDACTEUR
GROUP BY a.IDACTEUR
HAVING COUNT(s.IDSERVICE) = 1

--10. SELECT the input and out of 'Alert population'
SELECT s.SERVICENAME, v1.NAMEVARIABLE as input, v2.NAMEVARIABLE as output
FROM SERVICES s, SERVICEINPUT i, SERVICEOUTPUT o, VARIABLES v1, VARIABLES v2
WHERE s.IDSERVICE = i.IDSERVICE
AND s.IDSERVICE = o.IDSERVICE
AND i.NUMVARIABLE = v1.NUMVARIABLE
AND o.NUMVARIABLE = v2.NUMVARIABLE
AND s.SERVICENAME = 'Alert population';



